# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish NuGet

on:
  push:
    branches:
      -main
    
jobs:
  build:
    name: Update package
    runs-on: windows-latest

    steps:
    - name: Restore repository
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: |
        dotnet build WPF.Styles/WPF.Styles.csproj -c Release --no-restore
        dotnet build Tests/WPF.Styles.Tests/WPF.Styles.Tests.csproj -c Release --no-restore
      
    - name: Test
      run: dotnet test Tests/WPF.Styles.Tests/WPF.Styles.Tests.csproj --no-build --verbosity normal

    - name: Packing
      run: dotnet pack WPF.Styles/WPF.Styles.csproj --no-build -c Release -v q

    - name: Publishing
      run: dotnet nuget push WPF.Styles/bin/Release/*.nupkg -s https://api.nuget.org/v3/index.json -n --skip-duplicate -k ${{ secrets.NuGetApiKey }}
